- name: Parse show version
  ansible.utils.cli_parse:
    command: "show version"
    parser:
      name: ansible.netcommon.native
    set_fact: version_resources
# - name: Combine data into system_resources
#   ansible.builtin.set_fact:
#     system_resources: "{{ version_data | combine(resources_data, recursive=True) }}"
- name: Parse hostname
  ansible.utils.cli_parse:
    command: "show hostname"
    parser:
      name: ansible.netcommon.native
    set_fact: hostname_resources

- name: Combine data into system_resources
  ansible.builtin.set_fact:
    system_resources: "{{ version_resources | combine(hostname_resources, recursive=True) }}"
