- name: Parse show version
  ansible.utils.cli_parse:
    command: "show version"
    parser:
      name: ansible.netcommon.native
    set_fact: version_data

- name: Parse memory memory_summary
  ansible.utils.cli_parse:
    command: "show memory summary"
    parser:
      name: ansible.netcommon.native
    set_fact: memory_resources

- name: Combine data into system_resources
  ansible.builtin.set_fact:
    system_resources: "{{ version_data | combine(memory_resources, recursive=True) }}"
