---
- name: Set persist_result from all_gathered_facts
  ansible.builtin.set_fact:
    persist_result: "{{ all_gathered_facts }}"

- name: Include file write task
  ansible.builtin.include_tasks: write_to_file.yaml
  when:
    - all_gathered_facts != []
    - all_gathered_facts != {}
- name: Include file write task
  ansible.builtin.include_tasks: write_to_file.yaml
  when:
    - ignore_empty is defined
