---
- name: Run the platform facts module
  ansible.netcommon.network_resource:
    os_name: "{{ ansible_network_os }}"
    name: "{{ ansible_network_os }}_{{ res }}"
    state: gathered
  register: result

- name: Append to all results
  ansible.builtin.set_fact:
    persist_result: "{{ persist_result | default([]) | to_nice_yaml(indent=2) | from_yaml + [ dict([(res, result.gathered)]) ] }}"
