---
- name: Create inventory directory
  ansible.builtin.file:
    path: "{{ persist_inventory_path }}/host_vars/{{ inventory_hostname }}"
    state: directory
    mode: "0777"
  delegate_to: localhost

- name: Write persist resource to a file
  ansible.builtin.copy:
    content: "{{ persist_result}}"
    dest: "{{ persist_inventory_path }}/host_vars/{{ inventory_hostname }}.yaml"
    mode: "0777"
  delegate_to: localhost
