---
name: Integration-simple
on:
  pull_request_target:
    branches: [main]
    types:
      - labeled
      - opened
      - reopened
      - synchronize
    paths:
      - "plugins/**"
      - "tests/integration/**"
  workflow_dispatch:
jobs:
  lab_create:
    uses: ansible/ansible-content-actions/.github/workflows/cml_lab_create.yaml@main
    with:
      topology_path: tests/integration/labs/multi.yaml
      # lab_title_override: "Optional custom lab title"
    secrets:
      virl_host: ${{ secrets.VIRL_HOST }}
      virl_username: ${{ secrets.VIRL_USERNAME }} # optional; defaults to admin
      virl_password: ${{ secrets.VIRL_PASSWORD }}

  # TODO: Add a step to wait for tests to run

  lab_destroy:
    needs: lab_create
    uses: ansible/ansible-content-actions/.github/workflows/cml_lab_destroy.yaml@main
      # lab_title_override: "Optional custom lab title"
    secrets:
      virl_host: ${{ secrets.VIRL_HOST }}
      virl_username: ${{ secrets.VIRL_USERNAME }} # optional; defaults to admin
      virl_password: ${{ secrets.VIRL_PASSWORD }}
