jobs:
  cml-wait:
    uses: ansible/ansible-content-actions/.github/workflows/cml_wait.yaml@main
    with:
      topology_path: tests/integration/labs/multi.yaml
      # lab_title_override: "Optional custom lab title"
    secrets:
      virl_host: ${{ secrets.VIRL_HOST }}
      virl_username: ${{ secrets.VIRL_USERNAME }} # optional; defaults to admin
      virl_password: ${{ secrets.VIRL_PASSWORD }}
